- hosts: all                     # Cibler tous les hosts du groupe all (inventory)
  gather_facts: true             # Récupère les facts
  become: true                   # Superuser
  vars_files:
    - env.yml

  roles:
    - docker
    - create_network
    - launch_database
    - launch_app
    - launch_proxy
