- hosts: all                     # Cibler tous les hosts du groupe all (inventory)
  gather_facts: true             # Récupère les facts
  become: true                   # Superuser
  tasks:
    - name: Stop and remove all containers
      docker_container:
        name: "{{ item }}"       # Nom du conteneur à supprimer
        state: absent            # Le conteneur doit être absent (donc supprimé)
        force_kill: yes          # Forcer l'arrêt s'il tourne encore
      loop:
        - httpd                  # Liste des conteneurs à supprimer
        - simple-api
        - database
