name: Deploiement sur le serveur

on:
  workflow_run:
    workflows: ["CD devops 2025"] 
    types:
      - completed

jobs:
  # On fait ce job si le workflow "CD devops 2025" réussi et s'il a été run sur la branche main (implicitement par rapport aux autres workflows définis)
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          # Private SSH key to register in the SSH agen
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Déployer les conteneurs
        run: |
          cd TP3/ansible
          ansible-playbook -i inventories/setup.yml playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          
  
      
      
      
